'use client';
import { useEffect, useState, useMemo } from 'react';
import { Avatar, Card, Table, Tag, Progress, Button, Row, Col, Tooltip, Skeleton, message } from 'antd';
import { DownloadOutlined, ReloadOutlined, TrophyOutlined, WarningOutlined } from '@ant-design/icons';
import DashboardLayout from '../../../components/DashboardLayout';
import api from '../../../lib/api';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartTooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend, RadarChart, Radar, PolarGrid, PolarAngleAxis,
} from '../../../components/LazyCharts';

let _manager_reports_cache: { data: any; ts: number } | null = null;

const DEPT_COLORS = ['#6E473B', '#5A7A5A', '#7A6040', '#7A3A30', '#5A4A6A', '#4A6070'];

export default function ManagerReports() {
  const [team, setTeam] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/manager/team').then(r => setTeam(r.data)).catch(() => {}).finally(() => setLoading(false));
  }, []);

  // ── Computed values hoisted above exportToExcel to prevent ReferenceError ──
  const allGoals = team.flatMap(m => m.goals.map((g: any) => ({ ...g, employeeName: m.name, department: m.department })));
  const getProgressColor = (v: number) => v >= 80 ? '#5A7A5A' : v >= 60 ? '#7A6040' : '#7A3A30';
  const avgTeamProgress = allGoals.length ? Math.round(allGoals.reduce((s: number, g: any) => s + g.progressScore, 0) / allGoals.length) : 0;
  const completed = allGoals.filter((g: any) => g.progressScore >= 80).length;
  const approved = allGoals.filter((g: any) => g.isLocked || g.status === 'approved').length;
  const atRisk = allGoals.filter((g: any) => g.progressScore < 40).length;

  const exportToExcel = async () => {
    const XLSX = await import('xlsx');
    const wb = XLSX.utils.book_new();
    const today = new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' });
    const topPerf = team.length ? team.reduce((a:any,b:any)=>{
      const aAvg = a.goals.length ? a.goals.reduce((s:number,g:any)=>s+g.progressScore,0)/a.goals.length : 0;
      const bAvg = b.goals.length ? b.goals.reduce((s:number,g:any)=>s+g.progressScore,0)/b.goals.length : 0;
      return aAvg>bAvg?a:b;
    },team[0]) : null;
    const pendingCount = allGoals.filter((g:any)=>g.status==='submitted'&&!g.isLocked).length;
    const lockedCount = allGoals.filter((g:any)=>g.isLocked).length;

    // ── SHEET 1: Team Management Summary ──
    const summaryRows: any[][] = [
      ['GoalSync — Team Management Report'],
      ['Manager Performance Intelligence Summary'],
      ['Generated On:', today],
      ['Quarter:', 'Q3 FY 2024-25'],
      ['Report Type:', 'Manager Team Report'],
      ['Generated By:', 'GoalSync Leadership Platform'],
      [],
      ['TEAM KPI SUMMARY'],
      ['Metric', 'Value'],
      ['Team Size', team.length],
      ['Total Goals', allGoals.length],
      ['Team Avg Progress', `${avgTeamProgress}%`],
      ['Goals Approved / Locked', lockedCount],
      ['Goals Pending Review', pendingCount],
      ['Goals At Risk (<40%)', atRisk],
      ['Goals On Track (>=80%)', completed],
      ['Top Performer', topPerf ? `${topPerf.name} (${Math.round(topPerf.goals.reduce((s:number,g:any)=>s+g.progressScore,0)/Math.max(topPerf.goals.length,1))}% avg)` : 'N/A'],
      [],
      ['MEMBER-WISE PERFORMANCE SUMMARY'],
      ['Member Name', 'Department', 'Total Goals', 'Approved/Locked', 'Avg Progress %'],
      ...team.map((m:any)=>[
        m.name, m.department, m.goals.length,
        m.goals.filter((g:any)=>g.isLocked||g.status==='approved').length,
        m.goals.length ? Math.round(m.goals.reduce((s:number,g:any)=>s+g.progressScore,0)/m.goals.length) : 0,
      ]),
    ];
    const ws1 = XLSX.utils.aoa_to_sheet(summaryRows);
    ws1['!cols'] = [30,26,16,18,16].map(w=>({wch:w}));
    ws1['!merges'] = [{s:{r:0,c:0},e:{r:0,c:4}},{s:{r:1,c:0},e:{r:1,c:4}}];
    XLSX.utils.book_append_sheet(wb, ws1, '📊 Team Summary');

    // ── SHEET 2: Detailed Goal Table ──
    const detailRows: any[][] = [
      ['GoalSync — Detailed Team Goal Report'],
      [`Generated: ${today} | Quarter: Q3 FY 2024-25`],
      [],
      ['#','Employee','Department','Goal Title','Target','Achievement','Progress %','Weightage %','Status'],
      ...allGoals.map((g:any,i:number)=>[
        i+1, g.employeeName, g.department, g.goalTitle,
        g.target, g.achievement, Math.round(g.progressScore), g.weightage,
        g.isLocked?'LOCKED':g.status==='approved'?'APPROVED':g.status==='submitted'?'PENDING REVIEW':g.status.toUpperCase(),
      ]),
    ];
    const ws2 = XLSX.utils.aoa_to_sheet(detailRows);
    ws2['!cols'] = [5,22,16,34,10,12,12,12,16].map(w=>({wch:w}));
    ws2['!merges'] = [{s:{r:0,c:0},e:{r:0,c:8}},{s:{r:1,c:0},e:{r:1,c:8}}];
    XLSX.utils.book_append_sheet(wb, ws2, '📋 Detailed Goals');

    XLSX.writeFile(wb, `GoalSync_Team_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
    message.success('✅ Professional Team Report exported — 2 sheets!');
  };

  // Remaining analytics (topPerformer etc. depend on allGoals already computed above)

  const topPerformer = team.length ? team.reduce((best: any, m: any) => {
    const avg = m.goals.length ? m.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / m.goals.length : 0;
    const bestAvg = best.goals.length ? best.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / best.goals.length : 0;
    return avg > bestAvg ? m : best;
  }, team[0]) : null;

  const delayedPerformer = team.length ? team.reduce((worst: any, m: any) => {
    const avg = m.goals.length ? m.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / m.goals.length : 100;
    const worstAvg = worst.goals.length ? worst.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / worst.goals.length : 100;
    return avg < worstAvg ? m : worst;
  }, team[0]) : null;

  // Per-member summary for bar chart
  const memberData = team.map((m: any) => ({
    name: m.name.split(' ')[0],
    avg: m.goals.length ? Math.round(m.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / m.goals.length) : 0,
    approved: m.goals.filter((g: any) => g.isLocked || g.status === 'approved').length,
    total: m.goals.length,
  }));

  const statusDist = [
    { name: 'On Track (≥80%)', value: allGoals.filter((g: any) => g.progressScore >= 80).length, color: '#5A7A5A' },
    { name: 'Moderate (60-79%)', value: allGoals.filter((g: any) => g.progressScore >= 60 && g.progressScore < 80).length, color: '#7A6040' },
    { name: 'Behind (40-59%)', value: allGoals.filter((g: any) => g.progressScore >= 40 && g.progressScore < 60).length, color: '#7A6040' },
    { name: 'At Risk (<40%)', value: allGoals.filter((g: any) => g.progressScore < 40).length, color: '#7A3A30' },
  ].filter(d => d.value > 0);

  const deptData = Array.from(new Set(team.map((m: any) => m.department))).map((dept: any, i) => {
    const dGoals = allGoals.filter((g: any) => g.department === dept);
    return {
      dept: dept.length > 14 ? dept.substring(0, 14) + '…' : dept,
      progress: dGoals.length ? Math.round(dGoals.reduce((s: number, g: any) => s + g.progressScore, 0) / dGoals.length) : 0,
      count: dGoals.length, color: DEPT_COLORS[i % DEPT_COLORS.length],
    };
  });

  const quarterlyTrend = [
    { quarter: 'Q1', progress: 42, approvals: 8 },
    { quarter: 'Q2', progress: 61, approvals: 14 },
    { quarter: 'Q3', progress: avgTeamProgress, approvals: approved },
    { quarter: 'Q4', progress: 0, approvals: 0 },
  ];

  const radarData = team.map((m: any) => ({
    member: m.name.split(' ')[0],
    progress: m.goals.length ? Math.round(m.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / m.goals.length) : 0,
  }));

  const columns = [
    {
      title: 'Employee', render: (_: any, r: any) => (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Avatar size={32} style={{ background: '#6E473B', fontWeight: 700, fontSize: 13, flexShrink: 0 }}>{r.employeeName?.charAt(0)}</Avatar>
          <div>
            <div style={{ fontWeight: 700, fontSize: 13 }}>{r.employeeName}</div>
            <div style={{ fontSize: 11, color: '#A78D78' }}>{r.department}</div>
          </div>
        </div>
      ), width: 180,
    },
    { title: 'Goal', dataIndex: 'goalTitle', render: (v: string) => <span style={{ fontWeight: 600, fontSize: 13 }}>{v}</span> },
    { title: 'Target', dataIndex: 'target', width: 70 },
    { title: 'Achievement', dataIndex: 'achievement', width: 100, render: (v: number) => <strong style={{ color: '#5A7A5A' }}>{v}</strong> },
    {
      title: 'Progress', dataIndex: 'progressScore', width: 180, render: (v: number) => (
        <div>
          <Progress percent={Math.round(v)} size={6} strokeColor={getProgressColor(v)} showInfo={false} />
          <span style={{ fontSize: 11, fontWeight: 700, color: getProgressColor(v) }}>{Math.round(v)}%</span>
        </div>
      ),
    },
    { title: 'Wt.', dataIndex: 'weightage', width: 60, render: (v: number) => <strong>{v}%</strong> },
    {
      title: 'Status', width: 110, render: (_: any, r: any) => (
        <Tag color={r.isLocked ? 'blue' : r.status === 'approved' ? 'success' : r.status === 'submitted' ? 'warning' : 'default'} style={{ fontWeight: 600, fontSize: 11 }}>
          {r.isLocked ? '🔒 Locked' : r.status}
        </Tag>
      ),
    },
  ];

  return (
    <DashboardLayout role="manager">
      <div className="page-content">

        {/* ANALYTICS HERO */}
        <div style={{
          background: 'linear-gradient(135deg, #291C0E 0%, #291C0E 50%, #291C0E 100%)',
          borderRadius: 20, padding: '32px 40px', marginBottom: 24,
          boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 20 }}>
            <div>
              <div style={{ color: '#A78D78', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: 8 }}>
                📊 Leadership Intelligence Report
              </div>
              <h1 style={{ color: '#fff', fontSize: 28, fontWeight: 900, margin: '0 0 6px' }}>Team Performance Analytics</h1>
              <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: 13 }}>
                {team.length} team members · {allGoals.length} goals · FY 2024-25 · Q3 Active
              </div>
            </div>
            <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap', alignItems: 'center' }}>
              {[
                { label: 'Team Avg', value: `${avgTeamProgress}%`, color: '#A78D78' },
                { label: 'Approved', value: `${approved}/${allGoals.length}`, color: '#8AB08A' },
                { label: 'At Risk', value: atRisk, color: '#C07060' },
              ].map(kpi => (
                <div key={kpi.label} style={{
                  background: 'rgba(255,255,255,0.08)', borderRadius: 12, padding: '14px 22px', textAlign: 'center',
                  border: '1px solid rgba(255,255,255,0.12)', backdropFilter: 'blur(10px)',
                }}>
                  <div style={{ color: kpi.color, fontSize: 26, fontWeight: 900 }}>{kpi.value}</div>
                  <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: 11, fontWeight: 600, marginTop: 2 }}>{kpi.label}</div>
                </div>
              ))}
              <Button type="primary" icon={<DownloadOutlined />} onClick={exportToExcel}
                style={{ background: '#0284c7', border: 'none', borderRadius: 10, fontWeight: 700, height: 44, padding: '0 22px' }}>
                Export Excel
              </Button>
            </div>
          </div>
        </div>

        {/* Top / Delayed Performer Cards */}
        {team.length > 0 && (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 24 }}>
            {topPerformer && (
              <div style={{ background: 'linear-gradient(135deg,#EFF4EF,#EFF4EF)', border: '1px solid #B5C8B5', borderRadius: 16, padding: '20px 24px', display: 'flex', alignItems: 'center', gap: 16 }}>
                <div style={{ width: 52, height: 52, borderRadius: 14, background: '#5A7A5A', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24 }}>
                  <TrophyOutlined style={{ color: '#fff' }} />
                </div>
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#5A7A5A', textTransform: 'uppercase' }}>🏆 Top Performer</div>
                  <div style={{ fontWeight: 800, color: '#291C0E', fontSize: 16, margin: '4px 0' }}>{topPerformer.name}</div>
                  <div style={{ fontSize: 13, color: '#5A7A5A', fontWeight: 700 }}>
                    {Math.round(topPerformer.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / Math.max(topPerformer.goals.length, 1))}% avg progress
                  </div>
                </div>
              </div>
            )}
            {delayedPerformer && delayedPerformer.id !== topPerformer?.id && (
              <div style={{ background: 'linear-gradient(135deg,#F5EDDF,#F0E8D8)', border: '1px solid #C8B490', borderRadius: 16, padding: '20px 24px', display: 'flex', alignItems: 'center', gap: 16 }}>
                <div style={{ width: 52, height: 52, borderRadius: 14, background: '#7A6040', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24 }}>
                  <WarningOutlined style={{ color: '#fff' }} />
                </div>
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#6E473B', textTransform: 'uppercase' }}>⚠️ Needs Coaching</div>
                  <div style={{ fontWeight: 800, color: '#291C0E', fontSize: 16, margin: '4px 0' }}>{delayedPerformer.name}</div>
                  <div style={{ fontSize: 13, color: '#7A6040', fontWeight: 700 }}>
                    {Math.round(delayedPerformer.goals.reduce((s: number, g: any) => s + g.progressScore, 0) / Math.max(delayedPerformer.goals.length, 1))}% avg progress
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Charts Grid */}
        {allGoals.length > 0 && (
          <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', gap: 20, marginBottom: 24 }}>

            {/* Member Comparison */}
            <div style={{ background: '#fff', borderRadius: 16, padding: '20px', border: '1px solid #E1D4C2', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
              <div style={{ fontWeight: 700, color: '#291C0E', fontSize: 14, marginBottom: 4 }}>📊 Member Comparison</div>
              <div style={{ color: '#A78D78', fontSize: 11, marginBottom: 12 }}>Avg progress per team member</div>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={memberData} margin={{ top: 4, right: 8, bottom: 4, left: -20 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#F5F0EA" vertical={false} />
                  <XAxis dataKey="name" tick={{ fontSize: 11, fill: '#A78D78' }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 10 }} domain={[0, 100]} tickFormatter={v => `${v}%`} axisLine={false} tickLine={false} />
                  <RechartTooltip contentStyle={{ borderRadius: 10, fontSize: 12 }} />
                  <Bar dataKey="avg" name="Avg Progress %" fill="#6E473B" radius={[6, 6, 0, 0]} />
                  <Bar dataKey="approved" name="Approved Goals" fill="#5A7A5A" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Completion Donut */}
            <div style={{ background: '#fff', borderRadius: 16, padding: '20px', border: '1px solid #E1D4C2', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
              <div style={{ fontWeight: 700, color: '#291C0E', fontSize: 14, marginBottom: 4 }}>🍩 Progress Bands</div>
              <div style={{ color: '#A78D78', fontSize: 11, marginBottom: 8 }}>Team completion distribution</div>
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie data={statusDist} cx="50%" cy="45%" innerRadius={45} outerRadius={72} paddingAngle={3} dataKey="value">
                    {statusDist.map((entry, i) => <Cell key={i} fill={entry.color} />)}
                  </Pie>
                  <RechartTooltip contentStyle={{ borderRadius: 10, fontSize: 12 }} formatter={(v: any, n: any) => [v + ' goals', n]} />
                  <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 10 }} />
                </PieChart>
              </ResponsiveContainer>
            </div>

            {/* Quarterly Trend */}
            <div style={{ background: '#fff', borderRadius: 16, padding: '20px', border: '1px solid #E1D4C2', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
              <div style={{ fontWeight: 700, color: '#291C0E', fontSize: 14, marginBottom: 4 }}>📈 Quarterly Trend</div>
              <div style={{ color: '#A78D78', fontSize: 11, marginBottom: 8 }}>Team progress by quarter</div>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={quarterlyTrend} margin={{ top: 4, right: 8, bottom: 4, left: -20 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#F5F0EA" vertical={false} />
                  <XAxis dataKey="quarter" tick={{ fontSize: 11, fill: '#A78D78' }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 10 }} domain={[0, 100]} tickFormatter={v => `${v}%`} axisLine={false} tickLine={false} />
                  <RechartTooltip contentStyle={{ borderRadius: 10, fontSize: 12 }} />
                  <Bar dataKey="progress" name="Progress %" fill="#0284c7" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}

        {/* Team Completion Ratio Bar */}
        {allGoals.length > 0 && (
          <div style={{
            background: 'linear-gradient(135deg,#291C0E,#291C0E)', borderRadius: 16, padding: '20px 28px',
            marginBottom: 24, display: 'flex', alignItems: 'center', gap: 24,
          }}>
            <div style={{ color: '#A78D78', fontSize: 12, fontWeight: 700, whiteSpace: 'nowrap' }}>TEAM COMPLETION RATIO</div>
            <div style={{ flex: 1 }}>
              <div style={{ background: 'rgba(255,255,255,0.1)', borderRadius: 100, overflow: 'hidden', height: 14 }}>
                <div style={{
                  height: '100%', borderRadius: 100,
                  background: 'linear-gradient(90deg,#5A7A5A,#A78D78)',
                  width: `${Math.round((completed / Math.max(allGoals.length, 1)) * 100)}%`,
                  transition: 'width 1s ease',
                }} />
              </div>
            </div>
            <div style={{ color: '#fff', fontWeight: 900, fontSize: 20, whiteSpace: 'nowrap' }}>{completed}/{allGoals.length}</div>
            <div style={{ color: '#A78D78', fontWeight: 700, fontSize: 16 }}>{Math.round((completed / Math.max(allGoals.length, 1)) * 100)}%</div>
          </div>
        )}

        {/* Data Table */}
        <div style={{ background: '#fff', borderRadius: 16, border: '1px solid #E1D4C2', overflow: 'hidden', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
          <div style={{ padding: '18px 24px', borderBottom: '1px solid #F5F0EA', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <span style={{ fontWeight: 800, fontSize: 16, color: '#291C0E' }}>📋 Detailed Team Goal Report</span>
              <div style={{ fontSize: 12, color: '#A78D78', marginTop: 2 }}>{team.length} members · {allGoals.length} goals · FY 2024-25</div>
            </div>
          </div>
          <Table columns={columns} dataSource={allGoals} rowKey="id" loading={loading} pagination={{ pageSize: 15 }} size="middle" />
        </div>

      </div>
    </DashboardLayout>
  );
}