'use client';
import { useEffect, useState, useMemo, useCallback } from 'react';
import type { TablePaginationConfig } from 'antd/es/table/interface';
import { Card, Table, Tag, Progress, Select, Input, Button, Row, Col, Tabs, Tooltip as AntTooltip, Skeleton, Space, message } from 'antd';
import { DownloadOutlined, ReloadOutlined, BarChartOutlined, FileTextOutlined } from '@ant-design/icons';
import DashboardLayout from '../../../components/DashboardLayout';
import api from '../../../lib/api';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Legend, Cell, LabelList,
  AreaChart, Area, PieChart, Pie,
} from '../../../components/LazyCharts';

let _admin_reports_cache: { data: any; ts: number } | null = null;

const COLORS = ['#6E473B', '#5A7A5A', '#7A6040', '#5A4A6A', '#7A3A30', '#4A6070'];

const QUARTER_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  Q1: { bg: '#eff6ff', border: '#6E473B', text: '#291C0E' },
  Q2: { bg: '#EFF4EF', border: '#5A7A5A', text: '#3a3028' },
  Q3: { bg: '#291C0E', border: '#291C0E', text: 'white' },  // active
  Q4: { bg: '#fafafa', border: '#E1D4C2', text: '#A78D78' },
};

export default function AdminReports() {
  const [report, setReport] = useState<any[]>([]);
  const [completion, setCompletion] = useState<any>(null);
  const [analytics, setAnalytics] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [deptFilter, setDeptFilter] = useState('all');
  const [pagination, setPagination] = useState<TablePaginationConfig>({
    current: 1,
    pageSize: 15,
    pageSizeOptions: ['5', '10', '15', '20', '50'],
    showSizeChanger: true,
    showTotal: (total, range) => `${range[0]}–${range[1]} of ${total} goals`,
  });

  useEffect(() => {
    Promise.all([
      api.get('/reports/achievements'),
      api.get('/reports/completion'),
      api.get('/reports/analytics'),
    ])
      .then(([r1, r2, r3]) => { setReport(r1.data); setCompletion(r2.data); setAnalytics(r3.data); })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const departments = useMemo(() => ['all', ...new Set<string>(report.map(r => r.department).filter(Boolean))], [report]);
  const filtered = useMemo(() =>
    deptFilter === 'all' ? report : report.filter(r => r.department === deptFilter),
    [report, deptFilter]);

  const handleTableChange = useCallback((pag: TablePaginationConfig) => {
    setPagination(p => ({ ...p, current: pag.current, pageSize: pag.pageSize }));
  }, []);

  const avgProgress = useMemo(() =>
    filtered.length ? Math.round(filtered.reduce((s, r) => s + r.progressScore, 0) / filtered.length) : 0,
    [filtered]);

  const exportToExcel = async () => {
    const XLSX = await import('xlsx');
    const wb = XLSX.utils.book_new();
    const today = new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' });
    const topGoal = [...filtered].sort((a,b)=>b.progressScore-a.progressScore)[0];
    const needsAttention = [...filtered].sort((a,b)=>a.progressScore-b.progressScore)[0];
    const pending = filtered.filter(r=>r.status==='submitted'&&!r.isLocked).length;

    // ── SHEET 1: Executive Summary ──
    const summaryRows: any[][] = [
      ['GoalSync Enterprise — Executive Performance Report'],
      ['Organisation Goal Achievement Summary'],
      ['Generated On:', today],
      ['Quarter:', 'Q3 FY 2024-25'],
      ['Generated By:', 'GoalSync HR Platform'],
      ['Department Filter:', deptFilter === 'all' ? 'All Departments' : deptFilter],
      [],
      ['KEY PERFORMANCE INDICATORS'],
      ['Metric', 'Value'],
      ['Total Goals', filtered.length],
      ['Org Avg Progress', `${avgProgress}%`],
      ['Locked (Completed) Goals', totalLocked],
      ['Completion Rate', `${orgCompletion}%`],
      ['Pending Manager Review', pending],
      ['Best Performing Goal', topGoal ? `${topGoal.goalTitle} (${Math.round(topGoal.progressScore)}%)` : 'N/A'],
      ['Needs Attention', needsAttention ? `${needsAttention.goalTitle} (${Math.round(needsAttention.progressScore)}%)` : 'N/A'],
      [],
      ['DEPARTMENT PERFORMANCE RANKING'],
      ['Rank', 'Department', 'Avg Progress %', 'Goal Count', 'Locked Goals'],
      ...deptAggs.map((d,i) => [i+1, d.dept, `${d.avg}%`, d.count, d.locked]),
    ];
    const ws1 = XLSX.utils.aoa_to_sheet(summaryRows);
    ws1['!cols'] = [32, 28, 18, 14, 14].map(w=>({wch:w}));
    ws1['!merges'] = [
      {s:{r:0,c:0},e:{r:0,c:4}},
      {s:{r:1,c:0},e:{r:1,c:4}},
    ];
    XLSX.utils.book_append_sheet(wb, ws1, '📊 Executive Summary');

    // ── SHEET 2: Detailed Goal Report ──
    const headers = ['#','Employee Name','Department','Thrust Area','Goal Title','UoM Type','Target','Achievement','Progress %','Weightage %','Status'];
    const detailRows: any[][] = [
      ['GoalSync — Detailed Goal Achievement Report'],
      [`Generated: ${today} | Quarter: Q3 FY 2024-25 | Filter: ${deptFilter==='all'?'All Departments':deptFilter}`],
      [],
      headers,
      ...filtered.map((r,i) => [
        i+1,
        r.employeeName,
        r.department,
        r.thrustArea,
        r.goalTitle,
        r.uomType.toUpperCase(),
        r.target,
        r.achievement,
        Math.round(r.progressScore),
        r.weightage,
        r.isLocked ? 'LOCKED' : r.status === 'approved' ? 'APPROVED' : r.status === 'submitted' ? 'PENDING REVIEW' : r.status.toUpperCase(),
      ]),
    ];
    const ws2 = XLSX.utils.aoa_to_sheet(detailRows);
    ws2['!cols'] = [5,22,16,20,32,10,10,12,12,12,16].map(w=>({wch:w}));
    ws2['!merges'] = [{s:{r:0,c:0},e:{r:0,c:10}},{s:{r:1,c:0},e:{r:1,c:10}}];
    XLSX.utils.book_append_sheet(wb, ws2, '📋 Detailed Report');

    XLSX.writeFile(wb, `GoalSync_Executive_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
    message.success('✅ Professional Executive Report exported — 2 sheets!');
  };

  const exportToCSV = async () => {
    const XLSX = await import('xlsx');
    const ws = XLSX.utils.json_to_sheet(filtered.map(r => ({
      Employee: r.employeeName, Department: r.department, Goal: r.goalTitle,
      Target: r.target, Achievement: r.achievement, 'Progress%': Math.round(r.progressScore),
      Status: r.isLocked ? 'LOCKED' : r.status.toUpperCase(),
    })));
    const blob = new Blob([XLSX.utils.sheet_to_csv(ws)], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url;
    a.download = `GoalSync_${new Date().toISOString().split('T')[0]}.csv`; a.click();
    message.success('CSV exported!');
  };

  const getProgressColor = (v: number) => v >= 80 ? '#5A7A5A' : v >= 60 ? '#7A6040' : '#7A3A30';

  // Chart: group by employee for cleaner bar chart (top 8)
  const employeeChartData = useMemo(() => {
    const empMap: Record<string, { name: string; total: number; count: number; locked: number }> = {};
    filtered.forEach(r => {
      if (!empMap[r.employeeName]) empMap[r.employeeName] = { name: r.employeeName.split(' ')[0], total: 0, count: 0, locked: 0 };
      empMap[r.employeeName].total += r.progressScore;
      empMap[r.employeeName].count += 1;
      if (r.isLocked) empMap[r.employeeName].locked += 1;
    });
    return Object.values(empMap)
      .map(e => ({ name: e.name, avgProgress: Math.round(e.total / e.count), lockedGoals: e.locked }))
      .sort((a, b) => b.avgProgress - a.avgProgress)
      .slice(0, 8);
  }, [filtered]);

  const columns = [
    {
      title: '#', width: 44,
      render: (_: any, __: any, i: number) => (
        <span style={{ color: '#A78D78', fontWeight: 700 }}>
          {(((pagination.current ?? 1) - 1) * (pagination.pageSize ?? 15)) + i + 1}
        </span>
      ),
    },
    {
      title: 'Employee',
      dataIndex: 'employeeName',
      width: 160,
      render: (v: string, r: any) => (
        <div>
          <div style={{ fontWeight: 700, color: '#291C0E', fontSize: 13 }}>{v}</div>
          <div style={{ fontSize: 11, color: '#A78D78' }}>{r.department}</div>
        </div>
      ),
    },
    {
      title: 'Goal',
      dataIndex: 'goalTitle',
      render: (v: string, r: any) => (
        <div>
          <div style={{ fontWeight: 600, color: '#291C0E', fontSize: 13, lineHeight: 1.4 }}>{v}</div>
          <Tag style={{ fontSize: 10, borderRadius: 4, marginTop: 3 }}>{r.thrustArea}</Tag>
        </div>
      ),
    },
    { title: 'UoM', dataIndex: 'uomType', width: 80, render: (v: string) => <Tag color="geekblue" style={{ fontSize: 11 }}>{v.toUpperCase()}</Tag> },
    { title: 'Target', dataIndex: 'target', width: 70, render: (v: number) => <span style={{ fontWeight: 600 }}>{v}</span> },
    { title: 'Achieved', dataIndex: 'achievement', width: 85, render: (v: number) => <strong style={{ color: '#5A7A5A', fontSize: 15 }}>{v}</strong> },
    {
      title: 'Progress',
      dataIndex: 'progressScore',
      width: 160,
      sorter: (a: any, b: any) => a.progressScore - b.progressScore,
      render: (v: number) => {
        const pct = Math.round(v);
        return (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
              <span style={{ fontSize: 11, color: '#A78D78' }}></span>
              <span style={{ fontSize: 13, fontWeight: 800, color: getProgressColor(pct) }}>{pct}%</span>
            </div>
            <Progress percent={pct} strokeColor={getProgressColor(pct)} railColor="#F5F0EA" size={7} showInfo={false} />
          </div>
        );
      },
    },
    { title: 'Wt.', dataIndex: 'weightage', width: 65, render: (v: number) => <strong style={{ color: '#5A4A6A' }}>{v}%</strong> },
    {
      title: 'Status', width: 120,
      render: (_: any, r: any) => (
        <Tag
          color={r.isLocked ? 'blue' : r.status === 'approved' ? 'success' : r.status === 'submitted' ? 'warning' : 'default'}
          style={{ fontWeight: 700, borderRadius: 20, padding: '2px 10px' }}
        >
          {r.isLocked ? '🔒 Locked' : r.status === 'approved' ? '✅ Approved' : r.status === 'submitted' ? '📤 Submitted' : '📝 ' + r.status}
        </Tag>
      ),
    },
  ];

  // Top / weak department analytics
  const deptAggs = useMemo(() => {
    const map: Record<string, { total: number; count: number; locked: number }> = {};
    report.forEach(r => {
      if (!map[r.department]) map[r.department] = { total: 0, count: 0, locked: 0 };
      map[r.department].total += r.progressScore;
      map[r.department].count += 1;
      if (r.isLocked) map[r.department].locked += 1;
    });
    return Object.entries(map).map(([dept, d]) => ({
      dept, avg: Math.round(d.total / d.count), count: d.count, locked: d.locked,
    })).sort((a, b) => b.avg - a.avg);
  }, [report]);
  const topDept = deptAggs[0];
  const weakDept = deptAggs[deptAggs.length - 1];
  const totalLocked = report.filter(r => r.isLocked).length;
  const orgCompletion = report.length ? Math.round((totalLocked / report.length) * 100) : 0;

  return (
    <DashboardLayout role="admin">
      <div className="page-content">

        {/* EXECUTIVE REPORTING HERO */}
        <div style={{
          background: 'linear-gradient(135deg, #291C0E 0%, #3a2418 50%, #6E473B 100%)',
          borderRadius: 20, padding: '32px 40px', marginBottom: 24,
          boxShadow: '0 8px 32px rgba(41,28,14,0.35)',
        }}>
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', flexWrap:'wrap', gap:20 }}>
            <div>
              <div style={{ color:'#A78D78', fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.12em', marginBottom:8 }}>
                📊 Executive Leadership Reports
              </div>
              <h1 style={{ color:'#fff', fontSize:28, fontWeight:900, margin:'0 0 6px' }}>Achievement Reports</h1>
              <div style={{ color:'rgba(255,255,255,0.6)', fontSize:13 }}>
                FY 2024-25 · {filtered.length} goals · {departments.length - 1} departments
              </div>
            </div>
            <div style={{ display:'flex', gap:14, flexWrap:'wrap', alignItems:'center' }}>
              {[
                { label:'Org Avg Progress', value:`${avgProgress}%`, color:'#A78D78' },
                { label:'Total Goals', value:filtered.length, color:'#BEB5A9' },
                { label:'Completion Rate', value:`${orgCompletion}%`, color:'#C8A870' },
              ].map(kpi => (
                <div key={kpi.label} style={{ background:'rgba(255,255,255,0.1)', border:'1px solid rgba(255,255,255,0.15)', borderRadius:12, padding:'14px 20px', textAlign:'center' }}>
                  <div style={{ color:kpi.color, fontSize:26, fontWeight:900 }}>{kpi.value}</div>
                  <div style={{ color:'rgba(255,255,255,0.6)', fontSize:11, fontWeight:600, marginTop:2 }}>{kpi.label}</div>
                </div>
              ))}
              <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                <Button icon={<DownloadOutlined />} onClick={exportToCSV} style={{ background:'rgba(255,255,255,0.12)', border:'1px solid rgba(255,255,255,0.2)', color:'#fff', borderRadius:8, fontWeight:600 }}>CSV</Button>
                <Button type="primary" icon={<DownloadOutlined />} onClick={exportToExcel} style={{ background:'#291C0E', border:'none', borderRadius:8, fontWeight:700 }}>Export Excel</Button>
              </div>
            </div>
          </div>
        </div>

        {/* Dept Performance Cards */}
        {deptAggs.length > 1 && (
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:16, marginBottom:24 }}>
            {topDept && (
              <div style={{ background:'linear-gradient(135deg,#EFF4EF,#EFF4EF)', border:'1px solid #B5C8B5', borderRadius:16, padding:'20px 24px', display:'flex', alignItems:'center', gap:14 }}>
                <div style={{ width:52,height:52,borderRadius:14,background:'#5A7A5A',display:'flex',alignItems:'center',justifyContent:'center',fontSize:24 }}>🏆</div>
                <div>
                  <div style={{ fontSize:10,fontWeight:700,color:'#5A7A5A',textTransform:'uppercase' }}>Top Dept</div>
                  <div style={{ fontWeight:800,color:'#291C0E',fontSize:16,margin:'4px 0' }}>{topDept.dept}</div>
                  <div style={{ fontSize:13,color:'#5A7A5A',fontWeight:700 }}>{topDept.avg}% avg · {topDept.count} goals</div>
                </div>
              </div>
            )}
            {weakDept && weakDept.dept !== topDept?.dept && (
              <div style={{ background:'linear-gradient(135deg,#F5EDDF,#F0E8D8)', border:'1px solid #C8B490', borderRadius:16, padding:'20px 24px', display:'flex', alignItems:'center', gap:14 }}>
                <div style={{ width:52,height:52,borderRadius:14,background:'#7A6040',display:'flex',alignItems:'center',justifyContent:'center',fontSize:24 }}>⚠️</div>
                <div>
                  <div style={{ fontSize:10,fontWeight:700,color:'#6E473B',textTransform:'uppercase' }}>Needs Focus</div>
                  <div style={{ fontWeight:800,color:'#291C0E',fontSize:16,margin:'4px 0' }}>{weakDept.dept}</div>
                  <div style={{ fontSize:13,color:'#7A6040',fontWeight:700 }}>{weakDept.avg}% avg · {weakDept.count} goals</div>
                </div>
              </div>
            )}
            {/* Org Completion Ratio */}
            <div style={{ background:'linear-gradient(135deg,#1e3a8a,#291C0E)', borderRadius:16, padding:'20px 24px' }}>
              <div style={{ color:'#93c5fd',fontSize:11,fontWeight:700,textTransform:'uppercase',marginBottom:10 }}>ORG COMPLETION RATIO</div>
              <div style={{ background:'rgba(255,255,255,0.15)',borderRadius:100,overflow:'hidden',height:12,marginBottom:8 }}>
                <div style={{ height:'100%',borderRadius:100,background:'linear-gradient(90deg,#8AB08A,#6E473B)',width:`${orgCompletion}%`,transition:'width 1s' }} />
              </div>
              <div style={{ display:'flex',justifyContent:'space-between' }}>
                <span style={{ color:'rgba(255,255,255,0.6)',fontSize:12 }}>{totalLocked} locked of {report.length}</span>
                <span style={{ color:'#B5C8B5',fontWeight:900,fontSize:18 }}>{orgCompletion}%</span>
              </div>
            </div>
          </div>
        )}

        {/* Dept Ranking Strip */}
        {deptAggs.length > 0 && (
          <div style={{ background:'linear-gradient(135deg,#FAF7F4,#F5F0EA)', border:'1px solid #E1D4C2', borderRadius:14, padding:'16px 24px', marginBottom:24 }}>
            <div style={{ fontWeight:700,color:'#291C0E',fontSize:14,marginBottom:12 }}>🏅 Department Performance Ranking</div>
            <div style={{ display:'flex',gap:12,flexWrap:'wrap' }}>
              {deptAggs.map((d,i) => (
                <div key={d.dept} style={{
                  background: i===0?'#EFF4EF':i===deptAggs.length-1?'#F5EDDF':'white',
                  border:`1px solid ${i===0?'#B5C8B5':i===deptAggs.length-1?'#C8B490':'#E1D4C2'}`,
                  borderRadius:10, padding:'10px 16px', display:'flex', alignItems:'center', gap:10,
                }}>
                  <div style={{ fontWeight:900,color:'#A78D78',fontSize:13 }}>#{i+1}</div>
                  <div>
                    <div style={{ fontWeight:700,fontSize:13,color:'#291C0E' }}>{d.dept}</div>
                    <div style={{ fontSize:11,color: d.avg>=70?'#5A7A5A':d.avg>=50?'#7A6040':'#7A3A30', fontWeight:700 }}>{d.avg}% avg</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Q1–Q4 Completion Cards */}
        {completion && (
          <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
            {completion.quarterly.map((q: any) => {
              const isActive = q.quarter === 'Q3';
              const cfg = QUARTER_COLORS[q.quarter] || QUARTER_COLORS.Q4;
              return (
                <Col xs={12} sm={6} key={q.quarter}>
                  <div style={{
                    background: isActive ? cfg.bg : cfg.bg,
                    borderRadius: 14, padding: '18px 20px',
                    border: `2px solid ${cfg.border}`,
                    position: 'relative', overflow: 'hidden',
                    boxShadow: isActive ? '0 6px 20px rgba(30,64,175,0.25)' : 'none',
                  }}>
                    {isActive && (
                      <div style={{
                        position: 'absolute', top: 8, right: 10,
                        background: '#C8A870', color: '#291C0E',
                        fontSize: 9, fontWeight: 800, borderRadius: 6, padding: '2px 7px',
                      }}>
                        ACTIVE
                      </div>
                    )}
                    <div style={{ fontWeight: 800, fontSize: 22, color: isActive ? '#93c5fd' : cfg.text }}>
                      {q.quarter}
                    </div>
                    <div style={{ fontSize: 36, fontWeight: 900, color: isActive ? 'white' : cfg.text, lineHeight: 1.1, marginTop: 4 }}>
                      {q.checkins}
                    </div>
                    <div style={{ fontSize: 12, color: isActive ? 'rgba(255,255,255,0.7)' : '#A78D78', marginTop: 4 }}>
                      check-ins recorded
                    </div>
                    <Progress
                      percent={completion.goalSubmission?.total > 0
                        ? Math.min(100, Math.round((q.checkins / completion.goalSubmission.total) * 100)) : 0}
                      showInfo={false}
                      strokeColor={isActive ? '#93c5fd' : cfg.border}
                      railColor={isActive ? 'rgba(255,255,255,0.2)' : '#E1D4C2'}
                      size={5}
                      style={{ marginTop: 10 }}
                    />
                  </div>
                </Col>
              );
            })}
          </Row>
        )}

        {/* ── QoQ Trend Chart ── */}
        {analytics?.qoqTrends?.length > 0 && (
          <Card title={<span style={{ fontWeight: 700 }}>📈 Quarter-on-Quarter Achievement Trends by Department</span>}
            style={{ borderRadius: 16, marginBottom: 20 }}
            extra={<span style={{ fontSize: 11, color: '#A78D78' }}>Avg % actualAchievement from check-ins per quarter</span>}>
            <ResponsiveContainer width="100%" height={280}>
              <BarChart data={analytics.qoqTrends} margin={{ top: 14, right: 16, bottom: 10, left: 0 }} barSize={18} barGap={3}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F5F0EA" vertical={false} />
                <XAxis dataKey="department" tick={{ fontSize: 11, fill: '#A78D78', fontWeight: 600 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 11, fill: '#A78D78' }} domain={[0, 100]} axisLine={false} tickLine={false} tickFormatter={v => `${v}%`} />
                <Tooltip formatter={(v: any) => [`${v}%`, '']} contentStyle={{ borderRadius: 10, border: '1px solid #E1D4C2', fontSize: 12 }} />
                <Legend iconType="circle" iconSize={9} wrapperStyle={{ fontSize: 11 }} />
                <Bar dataKey="Q1" name="Q1" fill="#6E473B" radius={[4,4,0,0]} />
                <Bar dataKey="Q2" name="Q2" fill="#5A7A5A" radius={[4,4,0,0]} />
                <Bar dataKey="Q3" name="Q3" fill="#7A6040" radius={[4,4,0,0]} />
                <Bar dataKey="Q4" name="Q4" fill="#5A4A6A" radius={[4,4,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          </Card>
        )}

        {/* ── Department Heatmap ── */}
        {analytics?.deptHeatmap?.length > 0 && (
          <Card title={<span style={{ fontWeight: 700 }}>🔥 Department Completion Heatmap</span>}
            style={{ borderRadius: 16, marginBottom: 20 }}
            extra={<span style={{ fontSize: 11, color: '#A78D78' }}>Goal completion rate across all departments</span>}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))', gap: 12 }}>
              {analytics.deptHeatmap.map((d: any) => {
                const heat = d.completionRate >= 80 ? '#EFF4EF' : d.completionRate >= 50 ? '#F5EDDF' : '#F5ECEA';
                const heatBorder = d.completionRate >= 80 ? '#B5C8B5' : d.completionRate >= 50 ? '#C8B490' : '#C8A8A0';
                const heatText = d.completionRate >= 80 ? '#5A7A5A' : d.completionRate >= 50 ? '#7A6040' : '#7A3A30';
                return (
                  <div key={d.department} style={{ background: heat, border: `1px solid ${heatBorder}`, borderRadius: 12, padding: '14px 16px' }}>
                    <div style={{ fontWeight: 700, fontSize: 13, color: '#291C0E', marginBottom: 6 }}>{d.department}</div>
                    <div style={{ fontSize: 28, fontWeight: 900, color: heatText }}>{d.completionRate}%</div>
                    <div style={{ fontSize: 11, color: '#A78D78', marginTop: 2 }}>completion · {d.goalCount} goals</div>
                    <Progress percent={d.completionRate} strokeColor={heatText} railColor="rgba(0,0,0,0.06)" size={5} showInfo={false} style={{ marginTop: 8 }} />
                    <div style={{ display: 'flex', gap: 8, marginTop: 8, flexWrap: 'wrap' }}>
                      {[['✅', d.approved, '#5A7A5A'], ['🔒', d.locked, '#5A4A6A'], ['📤', d.submitted, '#7A6040'], ['📝', d.draft, '#A78D78']].map(([icon, val, col]) => (
                        <span key={String(icon)} style={{ fontSize: 10, fontWeight: 700, color: String(col) }}>{icon} {val}</span>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </Card>
        )}

        {/* ── Goal Distribution ── */}
        {analytics && (
          <Row gutter={[20, 20]} style={{ marginBottom: 20 }}>
            {/* By Thrust Area */}
            <Col xs={24} lg={10}>
              <Card title={<span style={{ fontWeight: 700 }}>🎯 Goals by Thrust Area</span>} style={{ borderRadius: 16 }}>
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={analytics.byThrustArea?.slice(0,8)} layout="vertical" margin={{ left: 8, right: 16 }} barSize={14}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#F5F0EA" horizontal={false} />
                    <XAxis type="number" tick={{ fontSize: 10, fill: '#A78D78' }} axisLine={false} tickLine={false} />
                    <YAxis dataKey="name" type="category" tick={{ fontSize: 10, fill: '#6E473B', fontWeight: 600 }} axisLine={false} tickLine={false} width={100} />
                    <Tooltip contentStyle={{ borderRadius: 10, fontSize: 12 }} />
                    <Bar dataKey="count" name="Goals" radius={[0,4,4,0]}>
                      {analytics.byThrustArea?.slice(0,8).map((_: any, i: number) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </Card>
            </Col>
            {/* By Status */}
            <Col xs={24} lg={7}>
              <Card title={<span style={{ fontWeight: 700 }}>📊 Goal Status Distribution</span>} style={{ borderRadius: 16 }}>
                {analytics.byStatus?.map((s: any) => {
                  const SMAP: Record<string,{color:string;icon:string}> = {
                    draft: {color:'#A78D78',icon:'📝'}, submitted: {color:'#7A6040',icon:'📤'},
                    approved: {color:'#5A7A5A',icon:'✅'}, rejected: {color:'#7A3A30',icon:'❌'},
                    rework: {color:'#5A4A6A',icon:'🔄'}, locked: {color:'#4A6070',icon:'🔒'},
                  };
                  const cfg = SMAP[s.status] ?? {color:'#A78D78',icon:'📋'};
                  const total = analytics.byStatus.reduce((a: number, b: any) => a + b.count, 0);
                  return (
                    <div key={s.status} style={{ marginBottom: 12 }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
                        <span style={{ fontSize: 12, color: '#A78D78', fontWeight: 600 }}>{cfg.icon} {s.status.charAt(0).toUpperCase() + s.status.slice(1)}</span>
                        <span style={{ fontSize: 13, fontWeight: 800, color: cfg.color }}>{s.count}</span>
                      </div>
                      <Progress percent={total > 0 ? Math.round((s.count / total) * 100) : 0} strokeColor={cfg.color} railColor="#F5F0EA" size={6} showInfo={false} />
                    </div>
                  );
                })}
              </Card>
            </Col>
            {/* By UoM */}
            <Col xs={24} lg={7}>
              <Card title={<span style={{ fontWeight: 700 }}>📐 Goals by UoM Type</span>} style={{ borderRadius: 16 }}>
                <ResponsiveContainer width="100%" height={220}>
                  <PieChart>
                    <Pie data={analytics.byUomType} dataKey="count" nameKey="name" cx="50%" cy="50%" outerRadius={80} label={({ name, percent }: any) => `${name} ${Math.round(percent*100)}%`} labelLine={false}>
                      {analytics.byUomType?.map((_: any, i: number) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                    </Pie>
                    <Tooltip contentStyle={{ borderRadius: 10, fontSize: 12 }} />
                  </PieChart>
                </ResponsiveContainer>
              </Card>
            </Col>
          </Row>
        )}

        {/* Charts Row */}
        <Row gutter={[20, 20]} style={{ marginBottom: 24 }}>
          <Col xs={24} lg={14}>
            <Card title={<span style={{ fontWeight: 700 }}>📈 Employee Achievement vs Progress</span>} style={{ borderRadius: 16 }}>
              <ResponsiveContainer width="100%" height={280}>
                <BarChart
                  data={employeeChartData}
                  margin={{ top: 20, right: 16, bottom: 10, left: 0 }}
                  barSize={28}
                  barGap={4}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#F5F0EA" vertical={false} />
                  <XAxis
                    dataKey="name"
                    tick={{ fontSize: 12, fill: '#A78D78', fontWeight: 600 }}
                    axisLine={false} tickLine={false}
                  />
                  <YAxis
                    tick={{ fontSize: 11, fill: '#A78D78' }}
                    domain={[0, 100]}
                    axisLine={false} tickLine={false}
                    tickFormatter={v => `${v}%`}
                  />
                  <Tooltip
                    formatter={(v: any, name: string) => [`${v}${name === 'avgProgress' ? '%' : ''}`, name === 'avgProgress' ? 'Avg Progress' : 'Locked Goals']}
                    contentStyle={{ borderRadius: 10, border: '1px solid #E1D4C2', fontSize: 13 }}
                  />
                  <Legend iconType="circle" iconSize={10} wrapperStyle={{ fontSize: 12 }} />
                  <Bar dataKey="avgProgress" name="Avg Progress %" fill="#6E473B" radius={[6, 6, 0, 0]}>
                    <LabelList
                      dataKey="avgProgress"
                      position="top"
                      style={{ fontSize: 11, fontWeight: 700, fill: '#374151' }}
                      formatter={(v: any) => `${v}%`}
                    />
                  </Bar>
                  <Bar dataKey="lockedGoals" name="Locked Goals" fill="#5A4A6A" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </Card>
          </Col>
          <Col xs={24} lg={10}>
            {completion && (
              <Card title={<span style={{ fontWeight: 700 }}>📊 Goal Lifecycle Summary</span>} style={{ borderRadius: 16, height: '100%' }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 14, padding: '8px 0' }}>
                  {[
                    { label: 'Total Goals', value: completion.goalSubmission?.total ?? 0, color: '#6E473B', icon: '🎯' },
                    { label: 'Submitted for Review', value: completion.goalSubmission?.submitted ?? 0, color: '#7A6040', icon: '📤' },
                    { label: 'Finalized & Locked', value: completion.goalSubmission?.locked ?? 0, color: '#5A4A6A', icon: '🔒' },
                  ].map(item => (
                    <div key={item.label} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                      <span style={{ fontSize: 22 }}>{item.icon}</span>
                      <div style={{ flex: 1 }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                          <span style={{ fontSize: 13, color: '#A78D78', fontWeight: 600 }}>{item.label}</span>
                          <span style={{ fontSize: 15, fontWeight: 800, color: item.color }}>{item.value}</span>
                        </div>
                        <Progress
                          percent={completion.goalSubmission?.total > 0
                            ? Math.round((item.value / completion.goalSubmission.total) * 100) : 0}
                          strokeColor={item.color}
                          railColor="#F5F0EA"
                          size={8}
                          showInfo={false}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            )}
          </Col>
        </Row>

        {/* Achievement Table */}
        <div style={{ background:'#fff', borderRadius:16, border:'1px solid #E1D4C2', overflow:'hidden', boxShadow:'0 2px 8px rgba(0,0,0,0.05)' }}>
          <div style={{ padding:'18px 24px', borderBottom:'1px solid #F5F0EA', display:'flex', justifyContent:'space-between', alignItems:'center', flexWrap:'wrap', gap:12 }}>
            <div>
              <span style={{ fontWeight:800, fontSize:16, color:'#291C0E' }}>📋 Detailed Achievement Report</span>
              <div style={{ fontSize:12, color:'#A78D78', marginTop:2 }}>{filtered.length} goals across {departments.length-1} departments</div>
            </div>
            <Space>
              <Select value={deptFilter} onChange={v => { setDeptFilter(v); setPagination(p => ({ ...p, current: 1 })); }} style={{ width: 180 }}>
                {departments.map(d => (<Select.Option key={d} value={d}>{d === 'all' ? 'All Departments' : d}</Select.Option>))}
              </Select>
              <Button icon={<DownloadOutlined />} onClick={exportToCSV}>CSV</Button>
              <Button type="primary" icon={<DownloadOutlined />} onClick={exportToExcel} style={{ fontWeight: 700 }}>Export Excel</Button>
            </Space>
          </div>
          <Table columns={columns} dataSource={filtered} rowKey="id" loading={loading}
            pagination={{ ...pagination, total: filtered.length }} onChange={handleTableChange}
            size="middle" scroll={{ x: 1100 }}
            rowClassName={(_, i) => i % 2 === 0 ? '' : 'table-row-alt'}
          />
        </div>
      </div>
    </DashboardLayout>
  );
}